server:
  port: 9000
zuul:
  routes:
    126:
      path: /126
      url: http://www.126.com
    baidu:
      path: /baidu
      url: https://www.baidu.com
    163:
      path: /163
      url: http://www.163.com