
spring:
  application:
    name: client
  rabbitmq:
    host: 127.0.0.1
    #端口号注意不是15672
    port: 5672
    username: guest
    password: guest
  #cloud:
    #stream:
      #bindings:
        #mySink:
         #myGroup: hello
         #contentType: text/plain
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/